url: https://ensinopmg.com.br
baseurl: /

# Site settings
title: EnsinoPMG
email: contato@ensinopmg.com.br
description: "Agência de aulas particulares com professores qualificados minuciosamente selecionados."


# Team names, titles and social links
people:
- name: Patricia Monteiro
  pic: paty
  position: CEO

- name: Daniel da Motta
  pic: dani
  position: Recrutamento e Seleção


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ensinopmg
  - title: facebook
    url: https://facebook.com/ensinopmg
  - title: instagram
    url: https://instagram.com/ensinopmg

# Postal address (add as many lines as necessary)
address:
  - line: Av das Américas, Barra da Tijuca
  - line: Rio de Janeiro, RJ, Brasil

# Build settings
markdown: kramdown
permalink: pretty
